name: CI
on:
  workflow_run:
    workflows: ["Data Crawling"]
    types:
      - completed
  workflow_dispatch:


permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v2

      - name: Install Packages
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train
        run: python train.py

      - name: Evaluation
        env:
          REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          mkdir Reports
          echo "## Model Metrics" > Reports/report_$(TZ=Asia/Seoul date +%Y_%m_%d).md
          cat ./Results/metrics_$(TZ=Asia/Seoul date +%Y_%m_%d).txt >> Reports/report_$(TZ=Asia/Seoul date +%Y_%m_%d).md
          cml comment create Reports/report_$(TZ=Asia/Seoul date +%Y_%m_%d).md

      - name: Update Branch
        env:
          NAME: ${{secrets.USER_NAME}}
          EMAIL: ${{secrets.USER_EMAIL}}
        run: |
          git config --global user.name "$NAME"
          git config --global user.email "$EMAIL"
          git add .
          git commit -m "Update with new results"
          git push --force origin HEAD:update

