name: Data Crawling

on:
  schedule:
    - cron: '0 15 * * *'

  workflow_dispatch:

permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout update branch
        uses: actions/checkout@v3
        with:
          ref: update

      - name: Install Packages
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Data Crawling
        run: python crawler.py

      - name: Commit and Push
        env:
          NAME: ${{secrets.USER_NAME}}
          EMAIL: ${{secrets.USER_EMAIL}}
        run: | 
          git config --global user.name "$NAME"
          git config --global user.email "$EMAIL"
          git add Data/
          git commit -m "Auto Data Crawling"
          git push
